let allMusic = [
  {
    name: "Roadtrip",
    artist: "Iamalex",
    link: "multimedia/songs/Lo-fi Para Estudiar/01 - Iamalex - Roadtrip.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Sunny Bliss",
    artist: "Emapea",
    link: "multimedia/songs/Lo-fi Para Estudiar/02 - Emapea - Sunny Bliss.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Sail",
    artist: "Moderator",
    link: "multimedia/songs/Lo-fi Para Estudiar/03 - Moderator - Sail.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "back when it all made sense",
    artist: "Middle School",
    link: "multimedia/songs/Lo-fi Para Estudiar/04 - Middle School - back when it all made sense.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Floaters",
    artist: "Brenky",
    link: "multimedia/songs/Lo-fi Para Estudiar/05 - Brenky - Floaters.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Amanita",
    artist: "Es-k",
    link: "multimedia/songs/Lo-fi Para Estudiar/06 - Es-k - Amanita.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Better, Together",
    artist: "Team Astro",
    link: "multimedia/songs/Lo-fi Para Estudiar/07 - Team Astro - Better, Together, Forever.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Onteora Lake",
    artist: "Kyle McEvoy",
    link: "multimedia/songs/Lo-fi Para Estudiar/08 - Kyle McEvoy - Onteora Lake.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Deer, Lion and Eagle",
    artist: "Arvnd",
    link: "multimedia/songs/Lo-fi Para Estudiar/09 - Arvnd - Deer, Lion and Eagle.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Pier",
    artist: "Slo Loris",
    link: "multimedia/songs/Lo-fi Para Estudiar/10 - Slo Loris - Pier.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Cherry",
    artist: "Pantone",
    link: "multimedia/songs/Lo-fi Para Estudiar/11 - Pantone - Cherry.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Cheat Sheet",
    artist: "Joe Corfield",
    link: "multimedia/songs/Lo-fi Para Estudiar/12 - Joe Corfield - Cheat Sheet.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "north shore",
    artist: "baechulgi",
    link: "multimedia/songs/Lo-fi Para Estudiar/13 - baechulgi - north shore.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Back When Marmots Used to Smoke",
    artist: "Flitz&Suppe",
    link: "multimedia/songs/Lo-fi Para Estudiar/14 - Flitz&Suppe - Back When Marmots Used to Smoke.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Cold Morning",
    artist: "LoFi Waiter",
    link: "multimedia/songs/Lo-fi Para Estudiar/15 - LoFi Waiter - Cold Morning.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "everything you say",
    artist: "MOMMY",
    link: "multimedia/songs/Lo-fi Para Estudiar/16 - MOMMY - everything you say.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Busy",
    artist: "Grenn",
    link: "multimedia/songs/Lo-fi Para Estudiar/17 - Grenn - Busy.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Desii",
    artist: "Mr Scroop",
    link: "multimedia/songs/Lo-fi Para Estudiar/18 - Mr Scroop - Desii.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Raw Quartet",
    artist: "Cookin Soul",
    link: "multimedia/songs/Lo-fi Para Estudiar/19 - Cookin Soul - Raw Quartet.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Pure",
    artist: "Soulone Beats",
    link: "multimedia/songs/Lo-fi Para Estudiar/20 - Soulone Beats - Pure.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "No Confusion",
    artist: "B dom",
    link: "multimedia/songs/Lo-fi Para Estudiar/21 - B dom - No Confusion.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Zamba",
    artist: "Mvdb",
    link: "multimedia/songs/Lo-fi Para Estudiar/22 - Mvdb - Zamba.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "i'm closing my eyes (feat. shiloh)",
    artist: "potsu",
    link: "multimedia/songs/Lo-fi Para Estudiar/23 - potsu - i'm closing my eyes (feat. shiloh).mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "The Girl With the Cappuccino",
    artist: "LoFi Waiter",
    link: "multimedia/songs/Lo-fi Para Estudiar/24 - LoFi Waiter - The Girl With the Cappuccino.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Affection",
    artist: "Jinsang",
    link: "multimedia/songs/Lo-fi Para Estudiar/25 - Jinsang - Affection.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Jazzy Afternoon",
    artist: "LoFi Waiter",
    link: "multimedia/songs/Lo-fi Para Estudiar/26 - LoFi Waiter - Jazzy Afternoon.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Floating Away",
    artist: "Altair Blake",
    link: "multimedia/songs/Lo-fi Para Estudiar/27 - Altair Blake - Floating Away.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "United We Belong",
    artist: "Frankly, We Hold",
    link: "multimedia/songs/Lo-fi Para Estudiar/28 - Frankly, We Hold - United We Belong.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Window Camping",
    artist: "mr_slace",
    link: "multimedia/songs/Lo-fi Para Estudiar/29 - mr_slace - Window Camping.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Cats come out at dusk",
    artist: "Ozelot",
    link: "multimedia/songs/Lo-fi Para Estudiar/30 - Ozelot - Cats come out at dusk.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Clocks",
    artist: "Pixie Dust",
    link: "multimedia/songs/Lo-fi Para Estudiar/31 - Pixie Dust - Clocks.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Calm Navy",
    artist: "Clap Cotton",
    link: "multimedia/songs/Lo-fi Para Estudiar/32 - Clap Cotton - Calm Navy.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Amaro",
    artist: "Koralle",
    link: "multimedia/songs/Lo-fi Para Estudiar/33 - Koralle - Amaro.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Blossom",
    artist: "Misc.Inc",
    link: "multimedia/songs/Lo-fi Para Estudiar/34 - Misc.Inc - Blossom.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Mirage",
    artist: "Rosko",
    link: "multimedia/songs/Lo-fi Para Estudiar/35 - Rosko - Mirage.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Last Light",
    artist: "Tabal",
    link: "multimedia/songs/Lo-fi Para Estudiar/36 - Tabal - Last Light.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Violet",
    artist: "Khutko",
    link: "multimedia/songs/Lo-fi Para Estudiar/37 - Khutko - Violet.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "their chair",
    artist: "Kudo",
    link: "multimedia/songs/Lo-fi Para Estudiar/38 - Kudo - their chair.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Wisteria Arbour",
    artist: "Raimu",
    link: "multimedia/songs/Lo-fi Para Estudiar/39 - Raimu - Wisteria Arbour.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Left Behind",
    artist: "Yasumu",
    link: "multimedia/songs/Lo-fi Para Estudiar/40 - Yasumu - Left Behind.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Picture on Their Mind (Instrumental)",
    artist: "KAINBEATS",
    link: "multimedia/songs/Lo-fi Para Estudiar/41 - KAINBEATS - Picture on Their Mind (Instrumental).mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Driving North",
    artist: "M e a d o w",
    link: "multimedia/songs/Lo-fi Para Estudiar/42 - M e a d o w - Driving North.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Snooze",
    artist: "INF",
    link: "multimedia/songs/Lo-fi Para Estudiar/43 - INF - Snooze.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Long Days",
    artist: "Softy",
    link: "multimedia/songs/Lo-fi Para Estudiar/44 - Softy - Long Days.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Lunch",
    artist: "ALH",
    link: "multimedia/songs/Lo-fi Para Estudiar/45 - ALH - Lunch.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Flying Over the Cuckoo's Nest",
    artist: "Lofi Coffee",
    link: "multimedia/songs/Lo-fi Para Estudiar/46 - Lofi Coffee - Flying Over the Cuckoo's Nest.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "8 AM",
    artist: "Dimension 32",
    link: "multimedia/songs/Lo-fi Para Estudiar/47 - Dimension 32 - 8 AM.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Seaglass",
    artist: "Yonderling",
    link: "multimedia/songs/Lo-fi Para Estudiar/48 - Yonderling - Seaglass.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Hyphenn",
    artist: "Muni",
    link: "multimedia/songs/Lo-fi Para Estudiar/49 - Muni - Hyphenn.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Secret Garden",
    artist: "Fenick",
    link: "multimedia/songs/Lo-fi Para Estudiar/50 - Fenick - Secret Garden.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Coral",
    artist: "Iamalex",
    link: "multimedia/songs/Lo-fi Para Estudiar/51 - Iamalex - Coral.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Natsukashii",
    artist: "Raimu",
    link: "multimedia/songs/Lo-fi Para Estudiar/52 - Raimu - Natsukashii.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Overgrown Piano",
    artist: "Mondo Loops",
    link: "multimedia/songs/Lo-fi Para Estudiar/53 - Mondo Loops - Overgrown Piano.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Ashcombe",
    artist: "Loafy Building",
    link: "multimedia/songs/Lo-fi Para Estudiar/54 - Loafy Building - Ashcombe.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "",
    artist: "So.Lo",
    link: "multimedia/songs/Lo-fi Para Estudiar/55 - So.Lo - Into The Fog.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "In The Zone",
    artist: "NO SPIRIT",
    link: "multimedia/songs/Lo-fi Para Estudiar/56 - NO SPIRIT - In The Zone.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Found You",
    artist: "Hoogway",
    link: "multimedia/songs/Lo-fi Para Estudiar/57 - Hoogway - Found You.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "A Little Help",
    artist: "HM Surf",
    link: "multimedia/songs/Lo-fi Para Estudiar/58 - HM Surf - A Little Help.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Down The Port",
    artist: "Miramare",
    link: "multimedia/songs/Lo-fi Para Estudiar/59 - Miramare - Down The Port.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
  {
    name: "Red String",
    artist: "Osaki",
    link: "multimedia/songs/Lo-fi Para Estudiar/60 - Osaki - Red String.mp3",
    image: "multimedia/songs/Lo-fi Para Estudiar/cover.jpg",
  },
];